[build-system]
requires = ["setuptools>=64", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "micrograd"
version = "0.12.5"
description = "A minimalistic autograd engine"
authors = [{ name = "Saksham Bedi", email = "hello@sakshambedi.com" }]
requires-python = ">=3.7"
